CREATE SCHEMA MISSAPP;

CREATE TABLE MISSAPP.USERS(
	NAME VARCHAR(256),
	PASSWORD VARCHAR(256),
	ADMIN INTEGER,
	PRIMARY KEY (NAME)
);

CREATE TABLE MISSAPP.QUESTIONS(
	TICKETID FLOAT,
	QUESTION VARCHAR(256),
	ANSWER VARCHAR(256),
	NAME VARCHAR(256),
	PRIMARY KEY (TICKETID)
);

DROP TABLE MISSAPP.USERS;