CREATE SCHEMA MISSAPP;

CREATE TABLE MISSAPP.USERS(
	NAME VARCHAR(256),
	PASSWORD VARCHAR(256),
	ADMIN INTEGER,
	PRIMARY KEY (NAME)
);

CREATE TABLE MISSAPP.QUESTIONS(
	TICKETID INTEGER,
	QUESTION VARCHAR(256),
	ANSWER VARCHAR(256),
	NAME VARCHAR(256),
	PRIMARY KEY (TICKETID)
);

ALTER TABLE MISSAPP.USERS
ADD salt VARCHAR(256);

DROP TABLE MISSAPP.USERS;
DROP TABLE MISSAPP.QUESTIONS;

ALTER TABLE MISSAPP.QUESTIONS
ALTER COLUMN TICKETID int;